apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  {{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
  {{- end }}
  {{- if .Values.labels }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
{{ toYaml .Values.matchLabels | indent 6 }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
{{ toYaml .Values.matchLabels | indent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}

      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}

      containers:
        # Main container
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.commands }}
          command: {{ toJson .Values.commands }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.envSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          {{- end }}

        # Sidecar container
        {{- if .Values.sidecar.enabled }}
        - name: {{ .Values.sidecar.name }}
          image: "{{ .Values.sidecar.image }}"
          imagePullPolicy: {{ .Values.sidecar.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.sidecar.ports }}
          ports:
{{ toYaml .Values.sidecar.ports | indent 12 }}
          {{- end }}
          {{- if .Values.sidecar.resources }}
          resources:
{{ toYaml .Values.sidecar.resources | indent 12 }}
          {{- end }}
          {{- if .Values.sidecar.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.sidecar.volumeMounts | indent 12 }}
          {{- end }}
        {{- end }}

      volumes:
{{ toYaml .Values.volumes | indent 8 }}
